version: '2'
services:
    agenda-app:
        image: agenda
        external_links:
            - agenda-postgresql:postgresql
            - agenda-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/agenda
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    agenda-postgresql:
        extends:
            file: postgresql.yml
            service: agenda-postgresql
    agenda-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: agenda-elasticsearch
