version: '2'
services:
    agenda-postgresql:
        container_name: agenda-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/agenda/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=agenda
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
